### ISSUE TITLE
Fall 2017 Event - Preliminary Quality Review

### ISSUE THREAD

**Issue by dudleycodes** [LacledesLAN/gamesvr-csgo-test#1]
- [x] Update MM / SM to latest
- [x] Make sure linux files are in `dist.linux` and that generic files are in `dist`
- [x] Verify advertisements works
- [x] Verify `sm_admin` works
- [x] Verify MOTD works
- [x] Verify your custom plugin is installed and working (dumps info to console on startup)
- [x] Verify LL config is loading
- [x] Verify fast downloads work

**Comment by JustinBenedick** [comment]
Updated sm/mm and sorted files  1b9cfd1

**Comment by JustinBenedick** [comment]
Skipped MOTD
